quarkus.application.name=vaiddf-api
quarkus.http.port=8080
quarkus.rest.path=/
quarkus.smallrye-health.path=/health
quarkus.micrometer.export.prometheus.enabled=true

quarkus.datasource.username=vaiddf
quarkus.datasource.password=vaiddf
quarkus.datasource.reactive.url=postgresql://localhost:5432/vaiddf

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.packages=com.vaiddf.api.entity
quarkus.log.level=INFO
